### ISSUE TITLE
cannot start tomcat correctly under output by "buildProduct" (Null Pointer ...)

### ISSUE THREAD

**Issue by tommyxu** [akhikhl/gretty#103]
2014-10-23 15:10:53,179 | INFO | T:main | org.apache.coyote.http11.Http11NioProtocol | DirectJDKLog.java:180
Initializing ProtocolHandler ["http-nio-7788"]

2014-10-23 15:10:53,204 | INFO | T:main | org.apache.tomcat.util.net.NioSelectorPool | DirectJDKLog.java:180
Using a shared selector for servlet write/read

2014-10-23 15:10:53,208 | INFO | T:main | org.apache.catalina.core.StandardService | DirectJDKLog.java:180
Starting service Tomcat

2014-10-23 15:10:53,209 | INFO | T:main | org.apache.catalina.core.StandardEngine | DirectJDKLog.java:180
Starting Servlet Engine: Apache Tomcat/8.0.14

2014-10-23 15:11:00,699 | ERROR | T:Tomcat-startStop-1 | org.apache.catalina.core.ContainerBase | DirectJDKLog.java:182
A child container failed during start

java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].Stand
ardHost[localhost].StandardContext[/]]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.7.0_65]
        at java.util.concurrent.FutureTask.get(FutureTask.java:188) [na:1.7.0_65]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916) ~[tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:868) [tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.14.jar:8.0.14]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardCon
text[/]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154) [tomcat-embed-core-8.0.14.jar:8.0.14]
        ... 6 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.apache.catalina.util.ExtensionValidator.validateApplication(ExtensionValidator.java:150) ~[tomcat-embed-core-8.0.14.jar:8
.0.14]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5047) ~[tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.14.jar:8.0.14]
        ... 6 common frames omitted
2014-10-23 15:11:00,703 | ERROR | T:main | org.apache.catalina.core.ContainerBase | DirectJDKLog.java:182
A child container failed during start

java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].Stand
ardHost[localhost]]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.7.0_65]
        at java.util.concurrent.FutureTask.get(FutureTask.java:188) ~[na:1.7.0_65]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916) ~[tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) [tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:439) [tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:760) [tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.14.jar:8.0.14]
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:340) [tomcat-embed-core-8.0.14.jar:8.0.14]

....

**Comment by akhikhl** [comment]
Hi Tommy,
Is the problem still reproducible on Gretty 1.1.8?
