### ISSUE TITLE
give start / stop port to distinguish two and more web applications to 

### ISSUE THREAD

**Issue by verystrongjoe** [akhikhl/gretty#127]
If I build and deploy two more applications and start two more applications in the deploy directory, first one can start, but the second one fails.

**Comment by akhikhl** [comment]
- Do you start web-applications on [farm](http://akhikhl.github.io/gretty-doc/#_multiple_web_apps)?
- Do you start web-applications via gradle or on a standalone servlet container?
- If you start via gradle, which tasks you invoke?
- Did you try setting different [httpPort/httpsPort](http://akhikhl.github.io/gretty-doc/Gretty-configuration.html) for each web-application?

**Comment by verystrongjoe** [comment]
Of course I gave different http/https port and used the farm. But I used
the buildProduct task of gradle for the deploy. There are two deployed
applications. First one was successful. But the followings wasn't.
2015. 1. 8. 오후 7:55에 "Andrey Hihlovskiy" <notifications@github.com>님이 작성:

**Comment by verystrongjoe** [comment]
D:\RedCA\workspace\jenkins_home\workspace\redca-aserver\build\output\redca-aserver>start.bat
2015. 1. 9 ?ㅼ쟾 10:55:42 org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
寃쎄퀬: Module [groovy-all] - Unable to load extension class [org.codehaus.groovy.runtime.NioGroovyMethods]
10:55:43.189 [main] DEBUG org.akhikhl.gretty.LauncherBase - servicePort: 9000, statusPort: 9001
10:55:43.329 [main] DEBUG org.akhikhl.gretty.LauncherBase - Sending "status" command to (probably) running server...
10:55:43.345 [main] DEBUG org.akhikhl.gretty.LauncherBase - Reading response...
10:55:43.345 [main] DEBUG org.akhikhl.gretty.LauncherBase - Got response: started
Exception in thread "main" java.lang.RuntimeException: Web-server is already running.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(Constructo
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
        at org.akhikhl.gretty.LauncherBase.launchThread(LauncherBase.groovy:190)
        at org.akhikhl.gretty.LauncherBase.launch(LauncherBase.groovy:71)
        at org.akhikhl.gretty.Launcher$launch.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at org.akhikhl.gretty.GrettyStarter.main(GrettyStarter.groovy:160)

I want to know the way for the GrettyStarter to take parameter for distinguish other loaded jvm.
