### ISSUE TITLE
onScanFilesChanged - wrong type

### ISSUE THREAD

**Issue by pete-experimenter** [akhikhl/gretty#128]
Using Gretty 1.1.8
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.akhikhl.gretty:gretty:1.1.8'
    }
}

repositories {
    jcenter()
}

if (!project.plugins.findPlugin(org.akhikhl.gretty.GrettyPlugin))
    project.apply(plugin: org.akhikhl.gretty.GrettyPlugin)

gretty {
    managedClassReload = true
    httpPort           = 8282
    servletContainer   = 'tomcat8' // 'jetty8'
    inplaceMode        = 'soft'
    jvmArgs            = ['-Xms128m', '-Xmx512m', '-XX:+HeapDumpOnOutOfMemoryError']
    onScanFilesChanged = {List<String> files->
        println "Some file changed: $files"
    }
}
```

Started the app with command
```
./gradlew -p templates-backend appRun --stacktrace
```
As a result I got an exception
```
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'build_dhs08jcx88di13sbi3zc9sgc7$_run_closure4_closure6@9e2c9e4' with class 'build_dhs08jcx88di13sbi3zc9sgc7$_run_closure4_closure6' to class 'java.util.List'
	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.setProperty(BeanDynamicObject.java:187)
	at org.gradle.api.internal.BeanDynamicObject.setProperty(BeanDynamicObject.java:112)
	at org.gradle.api.internal.CompositeDynamicObject.setProperty(CompositeDynamicObject.java:101)
	at org.akhikhl.gretty.GrettyExtension_Decorated.setProperty(Unknown Source)
	at build_dhs08jcx88di13sbi3zc9sgc7$_run_closure4.doCall(/path/to/file/build.gradle:39)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_dhs08jcx88di13sbi3zc9sgc7.run(/home/petr/programming/intellij/kleidoo-trunk/UI/devkit2/templates-backend/build.gradle:33)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
```
If I change the type of _onScanFilesChanged_ to list 
```
    onScanFilesChanged = [{List<String> files->
        println "Some file changed: $files"
    }]
```
it all works OK. According to documentation http://akhikhl.github.io/gretty-doc/Gretty-configuration.html#_onscanfileschanged _onScanFilesChanged_ is supposed to accept Closure type or have I misread it?

**Comment by aegliv** [comment]
This is also the case for the onScan an onStart tasks, both accept a list of closures.

Probably the documentation should be enhanced to state this detail...

**Comment by pete-experimenter** [comment]
@aegliv nice spotted!
