### ISSUE TITLE
Possible breakage with Gradle 2.4-nightly

### ISSUE THREAD

**Issue by jest** [akhikhl/gretty#154]
I'm not sure this is the problem of Gretty, but for me it looks like so.

When running with 2.3 everything works smoothly. When testing 2.4-20150325230033+0000 the error is being thrown:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':server-po'.
> Could not resolve all dependencies for configuration ':server-po:runtimeCopy'.
   > Could not resolve project :model.
     Required by:
         interlan:server-po:0.0.1
      > No such property: version for class: org.gradle.internal.component.local.model.DefaultProjectComponentSelector
   > Could not resolve project :webapi.
     Required by:
         interlan:server-po:0.0.1
      > No such property: version for class: org.gradle.internal.component.local.model.DefaultProjectComponentSelector
   > Could not resolve project :instance-po.
     Required by:
         interlan:server-po:0.0.1
      > No such property: version for class: org.gradle.internal.component.local.model.DefaultProjectComponentSelector
   > Could not resolve project :instance-frigo.
     Required by:
         interlan:server-po:0.0.1
      > No such property: version for class: org.gradle.internal.component.local.model.DefaultProjectComponentSelector

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

My gradle.build (part of multi-project setup):

```

// cannot use 'gretty' in 'plugins' due to conflict with 'war' plugin
// https://github.com/akhikhl/gretty/issues/114
// or with nebula.provided-base
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
		classpath 'org.akhikhl.gretty:gretty:1.2.0'
    }
}

plugins {
	id 'nebula.provided-base' version '2.0.1'
}

apply plugin: 'java'
apply plugin: 'org.akhikhl.gretty'

dependencies {
	compile project(':model')
	compile project(':webapi')
	compile project(':instance-po')
	compile project(':instance-frigo')
	
	provided 'javax.ws.rs:javax.ws.rs-api'

	compile 'org.jboss.resteasy:resteasy-servlet-initializer'
	compile 'org.jboss.resteasy:resteasy-guice'
	compile 'com.fasterxml.jackson.core:jackson-databind'
	compile 'com.google.inject:guice'
	runtime 'commons-collections:commons-collections'
}

gretty {
	contextPath = '/'
	interactiveMode = 'rebuildAndRestartOnKeyPress'
}

```

Removing all gretty-related stuff again make the project compile.

**Comment by jest** [comment]
The stacktrace suggests some API incompatible change:

```

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':server-po'.
> Could not resolve all dependencies for configuration ':server-po:runtimeCopy'.
   > Could not resolve project :model.
     Required by:
         interlan:server-po:0.0.1
      > No such property: version for class: org.gradle.internal.component.local.model.DefaultProjectComponentSelector
   > Could not resolve project :webapi.
     Required by:
         interlan:server-po:0.0.1
      > No such property: version for class: org.gradle.internal.component.local.model.DefaultProjectComponentSelector
   > Could not resolve project :instance-po.
     Required by:
         interlan:server-po:0.0.1
      > No such property: version for class: org.gradle.internal.component.local.model.DefaultProjectComponentSelector
   > Could not resolve project :instance-frigo.
     Required by:
         interlan:server-po:0.0.1
      > No such property: version for class: org.gradle.internal.component.local.model.DefaultProjectComponentSelector

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':server-po'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:486)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:116)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:54)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:34)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':server-po:runtimeCopy'.
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:52)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.rethrowFailure(DefaultResolvedConfiguration.java:36)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.getResolvedArtifacts(DefaultResolvedConfiguration.java:59)
	at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyResolver$FilesAggregatingResolvedConfiguration.getResolvedArtifacts(SelfResolvingDependencyResolver.java:90)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver$ErrorHandlingResolvedConfiguration.getResolvedArtifacts(ErrorHandlingArtifactDependencyResolver.java:212)
	at org.akhikhl.gretty.GrettyPlugin.addDependencies(GrettyPlugin.groovy:173)
	at org.akhikhl.gretty.GrettyPlugin.this$2$addDependencies(GrettyPlugin.groovy)
	at org.akhikhl.gretty.GrettyPlugin$this$2$addDependencies$2.callCurrent(Unknown Source)
	at org.akhikhl.gretty.GrettyPlugin.afterProjectEvaluate(GrettyPlugin.groovy:619)
	at org.akhikhl.gretty.GrettyPlugin.this$2$afterProjectEvaluate(GrettyPlugin.groovy)
	at org.akhikhl.gretty.GrettyPlugin$_apply_closure60_closure112.doCall(GrettyPlugin.groovy:718)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 28 more
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve project :model.
Required by:
    interlan:server-po:0.0.1
	at org.gradle.api.internal.artifacts.ivyservice.DependencySubstitutionResolver.resolve(DependencySubstitutionResolver.java:51)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ModuleVersionSelectorResolveState.resolveModuleRevisionId(DependencyGraphBuilder.java:880)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$DependencyEdge.resolveModuleRevisionId(DependencyGraphBuilder.java:231)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:118)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolveDependencyGraph(DependencyGraphBuilder.java:93)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:83)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultDependencyResolver$1.execute(DefaultDependencyResolver.java:125)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultDependencyResolver$1.execute(DefaultDependencyResolver.java:90)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:137)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:61)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:39)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultDependencyResolver.resolve(DefaultDependencyResolver.java:90)
	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:42)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:192)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:106)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:187)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:64)
	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:40)
	at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyResolver.resolve(SelfResolvingDependencyResolver.java:45)
	at org.gradle.api.internal.artifacts.ivyservice.ShortcircuitEmptyConfigsArtifactDependencyResolver.resolve(ShortcircuitEmptyConfigsArtifactDependencyResolver.java:58)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver.resolve(ErrorHandlingArtifactDependencyResolver.java:47)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolve(DefaultConfigurationResolver.java:46)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveNow(DefaultConfiguration.java:263)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:253)
	... 41 more
Caused by: groovy.lang.MissingPropertyException: No such property: version for class: org.gradle.internal.component.local.model.DefaultProjectComponentSelector
	at org.akhikhl.gretty.SpringBootResolutionStrategy$_resolveDependencyVersions_closure3_closure4.doCall(SpringBootResolutionStrategy.groovy:83)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultDependencySubstitutions$DependencyResolveDetailsWrapperAction.execute(DefaultDependencySubstitutions.java:266)
	at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultDependencySubstitutions$DependencyResolveDetailsWrapperAction.execute(DefaultDependencySubstitutions.java:255)
	at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:75)
	at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:75)
	at org.gradle.api.internal.artifacts.ivyservice.DependencySubstitutionResolver.resolve(DependencySubstitutionResolver.java:49)
	... 66 more

```

**Comment by akhikhl** [comment]
I just tried it on Gradle nightly 2.5-20150419220022. Config:

```groovy
wrapper {
  gradleVersion = "2.5-20150419220022+0000"
}
```

then:

```
./gradlew testAll
```

Everything compiles without errors. Tests run without errors.

Could you, please, try the same?

**Comment by jest** [comment]
This looks fine. Seems like Gradle problem, which was fixed with newer builds (i.e. your test works for me, when I only change the version to the tested by me `2.4-...` the build fails.

Thanks
