### ISSUE TITLE
Class reload breaks after one reload or so

### ISSUE THREAD

**Issue by levsa** [akhikhl/gretty#172]
Class reload works fine the first time, but second time (maybe more) I see this error:

```
2015-maj-13 15:46:36 org.springsource.loaded.agent.Watcher determineChangesSince
ALLVARLIG: FileWatcher caught serious error, see cause
java.lang.IllegalArgumentException: Can not set final java.util.Map field org.springframework.core.LocalVariableTableParameterNameDiscoverer.parameterNamesCache to org.springframework.core.LocalVariableTableParameterNameDiscoverer
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:146)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:150)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:37)
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:20)
	at java.lang.reflect.Field.get(Field.java:358)
	at org.springsource.loaded.agent.SpringPlugin.clearLocalVariableTableParameterNameDiscovererCache(SpringPlugin.java:186)
	at org.springsource.loaded.agent.SpringPlugin.reloadEvent(SpringPlugin.java:160)
	at org.springsource.loaded.TypeRegistry.fireReloadEvent(TypeRegistry.java:1794)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:417)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:845)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:51)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:235)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:219)
	at java.lang.Thread.run(Thread.java:695)
CHANGED: /Users/levsa/src/iipax-product/web/iwa/workspace/framework/build/libs/iwa-workspace-framework-5.7M1-SNAPSHOT.jar
Tooling API is using target Gradle version: 2.3.
```

**Comment by akhikhl** [comment]
Does your application use spring framework or spring boot?

**Comment by levsa** [comment]
Yes, it uses spring framework.

lör 16 maj 2015 kl 09:57 skrev Andrey Hihlovskiy <notifications@github.com>:

**Comment by akhikhl** [comment]
This seems to be known bug in springloaded library: https://github.com/spring-projects/spring-loaded/issues/73
It apprears with versions 1.2.1.RELEASE, 1.2.2.RELEASE, 1.2.3.RELEASE of springloaded.
Regrettably, switching to springloaded 1.1.5.RELEASE is not possible. When I try it with spring-boot 1.2.3.RELELEASE, other multiple errors appear.

**Comment by akhikhl** [comment]
Nevertheless, I can fix the "reloadability" problem, so that springloaded can be repeatedly used.

**Comment by levsa** [comment]
Thanks, but I managed to switch to an older release, 1.1-something, to get rid of this problem.

But because of permgen size increasing with each reload, I couldn't use live reload of classes. I haven't investigated the cause and given up on live reload of classes for now because of that.

**Comment by akhikhl** [comment]
switching to JDK 8 would eliminate permgen errors

**Comment by levsa** [comment]
Would it eliminate the leak? Is classes better GC:d in jdk8?
mån 18 maj 2015 kl. 00:05 skrev Andrey Hihlovskiy <notifications@github.com

**Comment by akhikhl** [comment]
I am not sure. I just saw that permgen parameters are no more required, nor supported by JDK 8.

**Comment by levsa** [comment]
Anyway, fixing the "reloadability" problem sounds good. Thanks!
