### ISSUE TITLE
Gretty Product Generation occurs Runtime Exception : A full JDK ( not just JRE) is required

### ISSUE THREAD

**Issue by verystrongjoe** [akhikhl/gretty#175]
I am urgent. So, I issued this even if I issued this on the stackoverflow. 

I am using gralde gretty for building my applications. And I needed to integrate 3 web apps using [gradle gretty producte generation][1]
 
Loading this grouped web application worked well with the following script. 

    apply plugin: 'java'
    apply plugin: 'application'
    apply plugin: 'war'
    apply plugin: 'org.akhikhl.gretty'
    
    buildscript{
    	repositories{
    		mavenLocal()
    		maven {
    			url maven_url
    			credentials {
    				username maven_username
    				password maven_password
    			}
    		 }
    	}
    	dependencies{
    		classpath "org.akhikhl.gretty:gretty:$gretty_version"
    	}
    }
    
    apply plugin: 'org.akhikhl.gretty'
    
    repositories {
    	mavenLocal()
    	maven {
    		url maven_url
    		credentials {
    			username maven_username
    			password maven_password
    		}
    	 }
    }
    
    // ###### Dependencies ########
    dependencies {
    	gretty group: 'commons-dbcp', name: 'commons-dbcp', version:'1.4'
    	gretty group: 'org.apache.activemq', name: 'activemq-all', version:'5.1.0'
    	gretty group: 'org.apache.derby', name: 'derby', version:derby_version
    }
    
    gretty {
    	  serverConfigFile = 'context-jetty-server.xml'
    	  jvmArgs = ['-Dderby.system.home=./blueappDB']
    	  loggingLevel = 'ALL'
    }
    
    farm{
    	port = Integer.parseInt(http_port)
    	servletContainer = servletContainer_type
    
    	webapp ':blueapp-server' , contextPath: "/blueapp_core", inplace: false 
    	webapp ':blueapp-pserver' , contextPath: "/plugin.server", inplace: false // inplace : false == war
    	webapp ':blueapp-aserver' , contextPath: "/agent.server", inplace: false // inplace : false == war
    }
    
    product {
    	webapp ':blueapp-server'
    	webapp ':blueapp-pserver'
    	webapp ':blueapp-aserver'
    }

But if I connect this web application on the browser.

    HTTP ERROR 500
    
    Problem accessing /plugin.server/. Reason:
    
        PWC6345: There is an error in invoking javac.  A full JDK (not just JRE) is required
    Caused by:
    
    org.apache.jasper.JasperException: PWC6345: There is an error in invoking javac.  A full JDK (not just JRE) is required
    	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:92)
    	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:378)
    	at 

But workarounds of this problem are so many one on the internet. Like they said, I confirmed my java path and set my environment variable, PATH to point the correct JDK directory.  But it had no problem.

So I changed the start.bat manually. What a surprise!! it worked well.
from 

    java.exe -Dfile.encoding=UTF8 -cp "%~dp0\conf\;%~dp0\starter\*" org.akhikhl.gretty.GrettyStarter %* start

to

    C:\Program Files\Java\jdk1.7.0_51\bin\java.exe -Dfile.encoding=UTF8 -cp "%~dp0\conf\;%~dp0\starter\*" org.akhikhl.gretty.GrettyStarter %* start

It's not the perfect workaround. There would be other perfect workaround for this. Besides, If I load this application using gretty-war-plugin separately, it worked even on the runtime. 

  [1]: http://akhikhl.github.io/gretty-doc/Product-generation.html

**Comment by akhikhl** [comment]
I guess this can be related to order of elements in PATH variable. Do you have both JRE and JDK on PATH? Which of them comes first?

**Comment by guillermo-varela** [comment]
Hi guys,

This is several months old, but might be useful to someone else :smile:

I just had this issue and it was because the Oracle installer added a symlink at the beginning of the PATH variable, which points to the JRE: C:\ProgramData\Oracle\Java\javapath\java.exe

Just check the path of the "java.exe" being used with the following command:
"where java"

If that command returns the path of the JRE or that symlink, change the value in the PATH variable using the JDK path.
