### ISSUE TITLE
Problem with farmRun and Gradle's configure-on-demand feature

### ISSUE THREAD

**Issue by fowlie** [akhikhl/gretty#196]
When using Gradle's [configure-on-demand feature](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:configuration_on_demand), farmRun no longer works. I've pasted [the full stack trace from Jetty7 here](http://pastebin.com/RBsEtKJU). 

Testing with Tomcat8 resulted in a more readable stacktrace:
```
10:14:29 ERROR Error configuring application listener of class org.springframework.web.context.ContextLoaderListener
java.lang.ClassNotFoundException: org.springframework.web.context.ContextLoaderListener
        at org.akhikhl.gretty.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:60) ~[gretty-runner-tomcat-1.2.1.jar:na]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157) ~[tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:520) ~[tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:501) ~[tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:120) ~[tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4650) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5166) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
```

However, farmRunWar and jettyRun still works on both Jetty and Tomcat.

Let me know if you're not able to reproduce the problem.

**Comment by akhikhl** [comment]
Hi,
I'll have a look.

**Comment by fedorovmv** [comment]
I have the same issue. It`s big problem for me because  configuring  without on-demand feature take long time (20+ minutes) :(
