### ISSUE TITLE
Gretty changes root project configuration even if it's only applied in subprojects (multi-project build)

### ISSUE THREAD

**Issue by Moritz90** [akhikhl/gretty#202]
Gretty adds javax.servlet:javax.servlet-api:3.1.0 and javax.websocket:javax.websocket-api:1.0 as dependencies to every single task in the root project although only two of the subprojects use gretty.

**Comment by Moritz90** [comment]
Some more details:

I'm currently loading gretty in the root project's build.gradle with the new plugins closure:
```groovy
plugins {
  id 'org.akhikhl.gretty' version '1.2.4'
}
```

Then, in two of the subprojects (it's a multi-project build), I apply the plugin:
```groovy
apply plugin: 'org.akhikhl.gretty'

gretty {
  // ... config here ...
}
```

Even though the gretty plugin is only applied in the subprojects, I've noticed the following configuration changes to the root project:

 * Every single task in the root project now depends on `javax.servlet:javax.servlet-api:3.1.0` and `javax.websocket:javax.websocket-api:1.0`
 * Running `gradle check` in the root directory now fails with the following stacktrace:
```
java.lang.RuntimeException: Web-server is already running.
        at org.akhikhl.gretty.LauncherBase.beforeLaunch(LauncherBase.groovy:91)
        at org.akhikhl.gretty.Launcher$beforeLaunch.call(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.action(StartBaseTask.groovy:40)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 57 more
```

**Comment by Moritz90** [comment]
Ok, seems like this is expected and I completely misunderstood what the new plugins{} closure actually does.
