### ISSUE TITLE
Error simple gettting started example

### ISSUE THREAD

**Issue by busylee999** [akhikhl/gretty#219]
I have tried example from Getting Started page as is and faced this error 
<code>Executing external task 'appRun'...
:prepareInplaceWebAppFolder
:createInplaceWebAppFolder
:compileJava
:processResources UP-TO-DATE
:classes
:prepareInplaceWebAppClasses
:prepareInplaceWebApp
:appRun
Download http://jcenter.bintray.com/org/akhikhl/gretty/gretty-runner-jetty9/1.2.4/gretty-runner-jetty9-1.2.4.pom
Download http://jcenter.bintray.com/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-webapp/9.2.10.v20150310/jetty-webapp-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-project/9.2.10.v20150310/jetty-project-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-parent/23/jetty-parent-23.pom
Download http://jcenter.bintray.com/org/akhikhl/gretty/gretty-runner-jetty/1.2.4/gretty-runner-jetty-1.2.4.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-jsp/9.2.10.v20150310/jetty-jsp-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-annotations/9.2.10.v20150310/jetty-annotations-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/javax-websocket-server-impl/9.2.10.v20150310/javax-websocket-server-impl-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-parent/9.2.10.v20150310/websocket-parent-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-server/9.2.10.v20150310/jetty-server-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-servlet/9.2.10.v20150310/jetty-servlet-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-security/9.2.10.v20150310/jetty-security-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-plus/9.2.10.v20150310/jetty-plus-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-xml/9.2.10.v20150310/jetty-xml-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/akhikhl/gretty/gretty-runner/1.2.4/gretty-runner-1.2.4.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/toolchain/jetty-schemas/3.1.M0/jetty-schemas-3.1.M0.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/toolchain/jetty-toolchain/1.4/jetty-toolchain-1.4.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-parent/18/jetty-parent-18.pom
Download http://jcenter.bintray.com/javax/servlet/jsp/javax.servlet.jsp-api/2.3.1/javax.servlet.jsp-api-2.3.1.pom
Download http://jcenter.bintray.com/org/glassfish/web/javax.servlet.jsp/2.3.2/javax.servlet.jsp-2.3.2.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/orbit/javax.servlet.jsp.jstl/1.2.0.v201105211821/javax.servlet.jsp.jstl-1.2.0.v201105211821.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/orbit/jetty-orbit/1/jetty-orbit-1.pom
Download http://jcenter.bintray.com/org/glassfish/web/javax.servlet.jsp.jstl/1.2.2/javax.servlet.jsp.jstl-1.2.2.pom
Download http://jcenter.bintray.com/org/glassfish/javax.el/3.0.0/javax.el-3.0.0.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/orbit/org.eclipse.jdt.core/3.8.2.v20130121/org.eclipse.jdt.core-3.8.2.v20130121.pom
Download http://jcenter.bintray.com/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/javax-websocket-client-impl/9.2.10.v20150310/javax-websocket-client-impl-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-server/9.2.10.v20150310/websocket-server-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-http/9.2.10.v20150310/jetty-http-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-io/9.2.10.v20150310/jetty-io-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-jndi/9.2.10.v20150310/jetty-jndi-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-util/9.2.10.v20150310/jetty-util-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.pom
Download http://jcenter.bintray.com/ch/qos/logback/logback-parent/1.1.3/logback-parent-1.1.3.pom
Download http://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.3.10/groovy-all-2.3.10.pom
Download http://jcenter.bintray.com/org/glassfish/javax.el/3.0.1-b08/javax.el-3.0.1-b08.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-client/9.2.10.v20150310/websocket-client-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-common/9.2.10.v20150310/websocket-common-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-servlet/9.2.10.v20150310/websocket-servlet-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.pom
Download http://jcenter.bintray.com/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.pom
Download http://jcenter.bintray.com/org/slf4j/slf4j-parent/1.7.7/slf4j-parent-1.7.7.pom
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-api/9.2.10.v20150310/websocket-api-9.2.10.v20150310.pom
Download http://jcenter.bintray.com/org/akhikhl/gretty/gretty-runner-jetty9/1.2.4/gretty-runner-jetty9-1.2.4.jar
Download http://jcenter.bintray.com/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-webapp/9.2.10.v20150310/jetty-webapp-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/akhikhl/gretty/gretty-runner-jetty/1.2.4/gretty-runner-jetty-1.2.4.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-jsp/9.2.10.v20150310/jetty-jsp-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-annotations/9.2.10.v20150310/jetty-annotations-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/javax-websocket-server-impl/9.2.10.v20150310/javax-websocket-server-impl-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-server/9.2.10.v20150310/jetty-server-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-servlet/9.2.10.v20150310/jetty-servlet-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-security/9.2.10.v20150310/jetty-security-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-plus/9.2.10.v20150310/jetty-plus-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-xml/9.2.10.v20150310/jetty-xml-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/akhikhl/gretty/gretty-runner/1.2.4/gretty-runner-1.2.4.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/toolchain/jetty-schemas/3.1.M0/jetty-schemas-3.1.M0.jar
Download http://jcenter.bintray.com/javax/servlet/jsp/javax.servlet.jsp-api/2.3.1/javax.servlet.jsp-api-2.3.1.jar
Download http://jcenter.bintray.com/org/glassfish/web/javax.servlet.jsp/2.3.2/javax.servlet.jsp-2.3.2.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/orbit/javax.servlet.jsp.jstl/1.2.0.v201105211821/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar
Download http://jcenter.bintray.com/org/glassfish/web/javax.servlet.jsp.jstl/1.2.2/javax.servlet.jsp.jstl-1.2.2.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/orbit/org.eclipse.jdt.core/3.8.2.v20130121/org.eclipse.jdt.core-3.8.2.v20130121.jar
Download http://jcenter.bintray.com/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/javax-websocket-client-impl/9.2.10.v20150310/javax-websocket-client-impl-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-server/9.2.10.v20150310/websocket-server-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-http/9.2.10.v20150310/jetty-http-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-io/9.2.10.v20150310/jetty-io-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-jndi/9.2.10.v20150310/jetty-jndi-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/jetty-util/9.2.10.v20150310/jetty-util-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar
Download http://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.3.10/groovy-all-2.3.10.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-client/9.2.10.v20150310/websocket-client-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-common/9.2.10.v20150310/websocket-common-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-servlet/9.2.10.v20150310/websocket-servlet-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.jar
Download http://jcenter.bintray.com/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
Download http://jcenter.bintray.com/org/eclipse/jetty/websocket/websocket-api/9.2.10.v20150310/websocket-api-9.2.10.v20150310.jar
Download http://jcenter.bintray.com/org/glassfish/javax.el/3.0.1-b08/javax.el-3.0.1-b08.jar
20.10.2015 0:44:21 org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [groovy-all] - Unable to load extension class [org.codehaus.groovy.runtime.NioGroovyMethods]
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jetty/security/DefaultAuthenticatorFactory : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2348)
	at java.lang.Class.getDeclaredFields(Class.java:1779)
	at org.codehaus.groovy.reflection.CachedClass$1$1.run(CachedClass.java:49)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.reflection.CachedClass$1.initValue(CachedClass.java:46)
	at org.codehaus.groovy.reflection.CachedClass$1.initValue(CachedClass.java:44)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
	at org.codehaus.groovy.reflection.CachedClass.getFields(CachedClass.java:255)
	at groovy.lang.MetaClassImpl.addFields(MetaClassImpl.java:2362)
	at groovy.lang.MetaClassImpl.inheritFields(MetaClassImpl.java:2357)
	at groovy.lang.MetaClassImpl.setupProperties(MetaClassImpl.java:2247)
	at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3254)
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3225)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:222)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:253)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:255)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:859)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:72)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:159)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.akhikhl.gretty.ServerManagerFactory.createServerManager(ServerManagerFactory.groovy:19)
	at org.akhikhl.gretty.ServerManagerFactory$createServerManager.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.akhikhl.gretty.Runner.run(Runner.groovy:106)
	at org.akhikhl.gretty.Runner.this$2$run(Runner.groovy)
	at org.akhikhl.gretty.Runner$this$2$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.akhikhl.gretty.Runner.main(Runner.groovy:46)
Exception in thread "Thread-14" org.gradle.process.internal.ExecException: Process 'command '/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:365)
	at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
	at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:159)
	at org.gradle.api.internal.project.AbstractProject.javaexec(AbstractProject.java:749)
	at org.gradle.api.internal.ProcessOperations$javaexec.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:361)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy:240)
	at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at groovy.lang.Closure.run(Closure.java:504)
	at java.lang.Thread.run(Thread.java:695)</code>

**Comment by vstoyanov** [comment]
Hi busylee,

You are probably running it with an unsupported JDK version - 51.0 is JDK7.

Best,
Vasil
