### ISSUE TITLE
A problem occurred evaluating script. > org.akhikhl.gretty.GrettyPlugin

### ISSUE THREAD

**Issue by khaidinh** [akhikhl/gretty#22]
# Issue

When using:

```
apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'
```

I get this error

```
FAILURE: Build failed with an exception.
* Where:
Script 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'
* What went wrong:
A problem occurred evaluating script.
> org.akhikhl.gretty.GrettyPlugin
```

Running gradle with stacktrace:

```
Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating script.
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
    at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:177)
... truncated rest...
Caused by: java.lang.NoClassDefFoundError: org.akhikhl.gretty.GrettyPlugin
    at gretty_3cssub2t750vfivp1ij8sq9a1r.class$(https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin)
    at gretty_3cssub2t750vfivp1ij8sq9a1r.$get$$class$org$akhikhl$gretty$GrettyPlugin(https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin)
    at gretty_3cssub2t750vfivp1ij8sq9a1r.run(https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin:17)
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
    ... 41 more
```
# Environment
- Ubuntu 13.10
- java version "1.7.0_55"
- Gradle 1.11
# Work around

I pasted in the script contents into my build file, commented out the 'if' block, then applied the 'gretty' plugin manually:

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.akhikhl.gretty:gretty-plugin:+'
    }
}

repositories {
    jcenter()
}

project.apply plugin: 'war'

//if (!project.plugins.findPlugin(org.akhikhl.gretty.GrettyPlugin))
//    project.apply(plugin: org.akhikhl.gretty.GrettyPlugin)

apply plugin: 'gretty'
```

**Comment by MarioMedel** [comment]
I'm having the same error

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\mmedel\Documents\Proyectos Spring con Angular 2\ng-workshop-starter\stuffmart\build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':stuffmart'.
> Could not read script 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'.
   > Server returned HTTP response code: 503 for URL: https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin
