### ISSUE TITLE
How do you configure ALPN with gretty?

### ISSUE THREAD

**Issue by the1plummie** [akhikhl/gretty#258]
I tried adding jvm arg:
```
    jvmArgs = [
        '-Xbootclasspath/p:/path/to/my/alpn-boot-8.1.6.v20151105.jar'
    ]
```
But it's still complaining about missing some class definitions that should be in alpn-boot already:
> Exception in thread "BigtableSession-startup-0" java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider
...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:245)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:263)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:739)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:319)
	at com.google.cloud.bigtable.grpc.BigtableSession.createSslContext(BigtableSession.java:122)
	at com.google.cloud.bigtable.grpc.BigtableSession.access$000(BigtableSession.java:82)
	at com.google.cloud.bigtable.grpc.BigtableSession$8.createChannel(BigtableSession.java:394)
	at com.google.cloud.bigtable.grpc.io.ReconnectingChannel$ChannelWrapper.<init>(ReconnectingChannel.java:90)
	at com.google.cloud.bigtable.grpc.io.ReconnectingChannel.<init>(ReconnectingChannel.java:219)
	at com.google.cloud.bigtable.grpc.io.ReconnectingChannel.<init>(ReingChannel.java:196)
	at com.google.cloud.bigtable.grpc.BigtableSession.createReconnectingChannel(BigtableSession.java:388)
	at com.google.cloud.bigtable.grpc.BigtableSession$7.create(BigtableSession.java:379)
	at com.google.cloud.bigtable.grpc.io.ChannelPool.<init>(ChannelPool.java:54)
	at com.google.cloud.bigtable.grpc.BigtableSession.createChannel(BigtableSession.java:376)
	at com.google.cloud.bigtable.grpc.BigtableSession.initializeDataClient(BigtableSession.java:330)
	at com.google.cloud.bigtable.grpc.BigtableSession.access$200(BigtableSession.java:82)
	at com.google.cloud.bigtable.grpc.BigtableSession$4.call(BigtableSession.java:291)
	at com.google.cloud.bigtable.grpc.BigtableSession$4.call(BigtableSession.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

Anybody got this to work?
Thx.

**Comment by saladinkzn** [comment]
Did you add ALPN dependecy?
e.g.:
`compile 'org.eclipse.jetty.alpn:alpn-api:1.1.2.v20150522'`

**Comment by the1plummie** [comment]
If I don't use gretty and just run embedded jetty app, I don't need to add that dependency, so not sure if that's needed.

but just to cover all cases, I also tried adding that dependency and run with gretty, and got a different error:
> Caused by: java.lang.Exception: Failed ALPN negotiation: Unable to find compatible protocol.
