### ISSUE TITLE
jetty appRun[Debug] crashes on run

### ISSUE THREAD

**Issue by cdaringe** [akhikhl/gretty#292]
# problem statement

i can't run gretty :(

# discussion

## demo/output

```
./gradlew appRun
:service:prepareInplaceWebAppFolder
:service:createInplaceWebAppFolder
...
:service:appRun
Error: Could not find or load main class org.akhikhl.gretty.Runner
Exception in thread "Thread-12" org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

## build.gradle

```
apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'

dependencies {
  ...
}
...
gretty {
  servletContainer = 'jetty7'
  httpPort 8083
}

...

buildscript {
  ...
}
```

**Comment by cdaringe** [comment]
i rolled back from gradle 3.0 to 2.12 and it worked ok.

**Comment by cdaringe** [comment]
nevermind, it re-surfaced today :(  there's some nuance in the system.  i'll see if i can't isolate it, but this is real bummery!

**Comment by cdaringe** [comment]
@akhikhl, is there any further information to provide that would aid in determining root cause here?  i'm not familiar with developing gradle plugins and running them locally such that I could effectively debug it on my own... _yet_

**Comment by cdaringe** [comment]
a co-worker had me hack the following in:

```gradle
   dependencies {
      classpath 'org.akhikhl.gretty:gretty:1.4.0'
 +    classpath 'org.akhikhl.gretty:gretty-runner:1.4.0'
    }
``

```gradle
    ...
    compile project(':core')
 +  grettyRunnerJetty7 'org.akhikhl.gretty:gretty-runner:1.4.0'
  }
  
```

it works, but for whatever reason, `gradle` isn't pulling down that transitive dependency.

**Comment by tzhotmail** [comment]
Hi @akhikhl  , I am getting the following error,  can you please advise what is wrong ?
`ipping task ':prepareArchiveWebApp' as it has no actions.
:prepareArchiveWebApp (Thread[Daemon worker,5,main]) completed. Took 0.0 secs.
:jettyRunWar (Thread[Daemon worker,5,main]) started.
:jettyRunWar
Putting task artifact state for task ':jettyRunWar' into context took 0.0 secs.
Executing task ':jettyRunWar' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
scanInterval is zero, hot deployment disabled
Starting process 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe''. Working directory: C:\OCGradle
Git\muocapp Command: C:\Program Files\Java\jdk1.8.0_60\bin\java.exe -Denv=DEV -Djava.security.egd=file:/dev
/./urandom -Dlogs.path=log -Dproperty.file.path=application.properties -XX:MaxPermSize=256m -Xdebug -Xms512
m -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\kama791\
.gradle\caches\modules-2\files-2.1\org.akhikhl.gretty\gretty-runner-jetty9\1.4.0\8bf22f19f73ea2dac810038d1f
384bdf8e84e2f1\gretty-runner-jetty9-1.4.0.jar org.akhikhl.gretty.Runner --servicePort=56794 --statusPort=56
795 --serverManagerFactory=org.akhikhl.gretty.ServerManagerFactory
Successfully started process 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe''
Error: Could not find or load main class org.akhikhl.gretty.Runner
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Exception in thread "Thread-9" org.gradle.process.internal.ExecException: Process 'command 'C:\Program File
s\Java\jdk1.8.0_60\bin\java.exe'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHa
ndle.java:369)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
        at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:170)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:943)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:939)
        at org.gradle.api.Project$javaexec$4.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy:256)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at groovy.lang.Closure.run(Closure.java:495)
        at java.lang.Thread.run(Thread.java:745)
Closing daemon's stdin at end of input.
Terminate batch job (Y/N)? Y`

My build Script is as follows `buildscript{
	repositories{
		maven {
			url "http://maven3.ksm.nsroot.net:8081/nexus/content/repositories/central"
		}
	}
	dependencies{
		//classpath "com.netflix.nebula:gradle-ospackage-plugin:3.2.1"
		classpath 'org.akhikhl.gretty:gretty:1.4.0'
		classpath 'org.akhikhl.gretty:gretty-core:1.4.0'
        classpath 'org.akhikhl.gretty:gretty-runner:1.4.0'
        classpath 'org.akhikhl.gretty:gretty-runner-jetty9:1.4.0'		
	}
	
}`

**Comment by dazzbourgh** [comment]
Having the same issue on the latest version, any updates?

The output:

`Error: Could not find or load main class org.akhikhl.gretty.Runner
Exception in thread "Thread-29" org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_201\bin\java.exe'' finished with
non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:396)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:37)
        at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:227)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1105)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1100)
        at org.gradle.api.Project$javaexec$6.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:93)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy:259)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.run(Closure.java:492)
        at java.lang.Thread.run(Thread.java:748)
`
