### ISSUE TITLE
Gretty and Gradle 3

### ISSUE THREAD

**Issue by gregorko** [akhikhl/gretty#300]
When using Gradle 3.x I see the following error when I use my own configuration:
Project :app declares a dependency from configuration 'myConfig' to configuration 'myConfig' which is not declared in the descriptor for project :level1:level2.

When using Gradle 2.14.1 everything is fine. Also everything is fine when I don't apply the Gretty plugin. Therefor I assume it might be a Gretty problem.

Attached is the stripped down example project.

[Gradle3GrettyProblem.zip](https://github.com/akhikhl/gretty/files/529346/Gradle3GrettyProblem.zip)

**Comment by pburgmer** [comment]
Would be great if Gretty was able to run with Gradle 3. Any updates or comments on that?

**Comment by johnjaylward** [comment]
I see this same issue with gretty on Gradle 3. Any update from the gradle owners on maintaining this?

**Comment by h3adache** [comment]
I commented in #306 that it works fine for me in Gradle 3.3 but just to look I downloaded and ran `./gradlew apprun` on your zip file. and it works fine? 

```
10:33:27 INFO  Jetty 9.2.15.v20160210 started and listening on port 8080
10:33:27 INFO  app runs at:
10:33:27 INFO    http://localhost:8080/app
Press any key to stop the server.
```
What are you trying to run?

**Comment by johnjaylward** [comment]
```groovy
buildscript {
    dependencies {
        // jetty/tomcat integration
        classpath 'org.akhikhl.gretty:gretty:+'
    }
}

apply plugin: 'war'
apply plugin: 'org.akhikhl.gretty'

gretty {
    servletContainer = 'tomcat7'
    contextPath = '/'
    //    contextConfigFile="$projectDir/src/test/resources/jetty-env.xml"
    contextConfigFile = "$projectDir/src/test/resources/tomcat-context.xml"

    fastReload = false
    recompileOnSourceChange = false
    reloadOnClassChange = false
    reloadOnConfigChange = false
    reloadOnLibChange = false

    enableNaming = true

    debugSuspend = false

    //extraResourceBase "${project.buildDir}/scripts"
    extraResourceBase "${projectDir}/src/test/resources/"

    afterEvaluate {
        // here we can access Gretty tasks
        println "******** GRETTY afterEvaluate **********"
        (project.configurations.providedCompile + project.configurations.providedRuntime).collect().each {
            println "******GRETTY******** $it ****************************"
            appRun.classPath it
            appRunWar.classPath it
            appRunDebug.classPath it
            appRunWarDebug.classPath it
        }
        appRun.classPath "${projectDir}/src/test/resources/"
        appRunWar.classPath "${projectDir}/src/test/resources/"
        appRunDebug.classPath "${projectDir}/src/test/resources/"
        appRunWarDebug.classPath "${projectDir}/src/test/resources/"
    }
}
```

Removing my entire `gretty {...}` block doesn't fix the issue in 3.3. Nothing short of removing the entire plugin seems to work.

**Comment by johnjaylward** [comment]
I tried switching to this:
```goovy
buildscript {
    dependencies {
        // jetty integration
        //classpath 'org.akhikhl.gretty:gretty:+'
    }
}

plugins { id 'org.akhikhl.gretty' version '1.4.0' }
apply plugin: 'war'
//apply plugin: 'org.akhikhl.gretty'
... more config
```
and it still fails with the modifying provided compile error. 

I don't see how you are getting it to work. Even in 2.14.1 I see the warning that the configuration will be removed in 3.0.

It doesn't matter what task I run. `./gradlw clean` or `./gradlew wrapper` all exhibit the same behavior.

**Comment by h3adache** [comment]
@johnjaylward I removed `contextConfigFile = "$projectDir/src/test/resources/tomcat-context.xml"` since I obviously don't have that file:

```
******** GRETTY afterEvaluate **********
******GRETTY******** /home/tchen/.gradle/caches/modules-2/files-2.1/javax.servlet/javax.servlet-api/3.0.1/6bf0ebb7efd993e222fc1112377b5e92a13b38dd/javax.servlet-api-3.0.1.jar ****************************
```
10:51:53 INFO  Tomcat 7.0.68 started and listening on port 8080
10:51:53 INFO   runs at:
10:51:53 INFO    http://localhost:8080
Press any key to stop the server.
```
I took out the config for my own web app and replaced it with your config minus that line that I mentioned above.

My environment:

```
------------------------------------------------------------
Gradle 3.3
------------------------------------------------------------

Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_67 (Oracle Corporation 24.65-b04)
OS:           Linux 3.10.0-327.36.3.el7.x86_64 amd64
```

**Comment by johnjaylward** [comment]
your system is apparently magic. I remove the same line, but still get this error:

```./gradlew wrapper

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':proj-struts'.
> Cannot change dependencies of configuration ':proj-struts:providedCompile' after it has been included in dependency resolution.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.737 secs
```

Specs are:
```
Gradle 3.3

Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 10 10.0 amd64```

**Comment by johnjaylward** [comment]
Here's the stack trace which shows it's originating from Gretty:
```
./gradlew wrapper --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':proj-struts'.
> Cannot change dependencies of configuration ':proj-struts:providedCompile' after it has been included in dependency resolution.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':proj-struts'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:244)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:217)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.InvalidUserDataException: Cannot change dependencies of configuration ':proj-struts:providedCompile' after it has been included in dependency resolution.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:741)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.extendsFrom(DefaultConfiguration.java:272)
        at org.akhikhl.gretty.GrettyPlugin.addConfigurationsAfterEvaluate(GrettyPlugin.groovy:75)
        at org.akhikhl.gretty.GrettyPlugin.afterProjectEvaluate(GrettyPlugin.groovy:695)
        at org.akhikhl.gretty.GrettyPlugin$_apply_closure63$_closure114.doCall(GrettyPlugin.groovy:799)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy14.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
        ... 48 more


BUILD FAILED

Total time: 7.169 secs
```

**Comment by johnjaylward** [comment]
@h3adache , are you also applying the war plugin to the same project that you are applying gretty?

I just tried removing the war plugin, and it appears to get past the "provided compile" bug, but then gives me a different one:

```
Caused by: org.gradle.api.InvalidUserDataException: Cannot change strategy of configuration ':proj-struts:compile' after it has been resolved.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:732)
        at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy.eachDependency(DefaultResolutionStrategy.java:130)
        at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy_Decorated.eachDependency(Unknown Source)
        at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy_Decorated$eachDependency.call(Unknown Source)
        at org.akhikhl.gretty.SpringBootResolutionStrategy$_resolveDependencyVersions_closure3.doCall(SpringBootResolutionStrategy.groovy:82)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:117)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:122)
        at org.gradle.api.DomainObjectCollection$all.call(Unknown Source)
        at org.akhikhl.gretty.SpringBootResolutionStrategy.resolveDependencyVersions(SpringBootResolutionStrategy.groovy:81)
        at org.akhikhl.gretty.SpringBootResolutionStrategy.apply(SpringBootResolutionStrategy.groovy:30)
        at org.akhikhl.gretty.SpringBootResolutionStrategy$apply.call(Unknown Source)
        at org.akhikhl.gretty.GrettyPlugin.addConfigurationsAfterEvaluate(GrettyPlugin.groovy:76)
        at org.akhikhl.gretty.GrettyPlugin.afterProjectEvaluate(GrettyPlugin.groovy:695)
        at org.akhikhl.gretty.GrettyPlugin$_apply_closure63$_closure114.doCall(GrettyPlugin.groovy:799)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy14.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
        ... 48 more
```

**Comment by h3adache** [comment]
lol maybe so. @gregorko's configuration worked fine for me as well without any modifications. That's the same error as in #306 but he's using a different configuration style.

**Comment by akhikhl** [comment]
Hello guys, I'll fix Gretty compatibility to Gradle 3.3 in the coming release 1.4.1 (scheduled for 1 of February, 2017).

**Comment by johnjaylward** [comment]
Thank you!

**Comment by akhikhl** [comment]
@gregorko , the issue you describe is not Gretty-specific. Please consider conditions:

* app includes myConfig artifact from level1:level2:

```groovy
myConfig project(path: ':level1:level2', configuration:'myConfig')
```

* level2 does not define myConfig configuration. Instead, level1 does.

**Comment by akhikhl** [comment]
@johnjaylward , can you provide a toy project, allowing to reproduce the problem?

**Comment by johnjaylward** [comment]
@akhikhl here is a sample project.

I narrowed the incompatibility with my configuration and gretty at this spot: https://github.com/johnjaylward/gretty-3-fail/blob/master/proj-web/build.gradle#L54

What my aim is there is to explode the generated shared-resources jar and directly include those "shared resources" within the current project. In reality, I should probably just do a file-tree of the shared-resource project directory and include them directly that way. My "shared-resources" do not _need_ to generate a jar at all. There is no actual compilation happening there.

Now that I narrowed down the issue, I'm not sure it's something you should change in gretty unless you can do your plug-in modifications before resource evaluations.

It does seem that a few others are having a similar issue though, but standard usage of the gretty plugin appears to be fine on 3.3.

**Comment by akhikhl** [comment]
@johnjaylward , you should have opened a separate issue for this, since it has nothing to do with Gretty and Gradle 3. However, here is the solution:

```groovy
processResources {
  dependsOn ':proj-shared-resources:jar'
    filter (ReplaceTokens, tokens: [
        "project.version": project.property('version')
    ])
    from { zipTree(project.configurations.compile.find { it.name.endsWith("shared-resources-${project.version}.jar") }) }
}
```

Explanation:

* I replaced `()` with `{}` in the "from" call - this postpones resolution of the compile configuration until later stage.
* I added `dependsOn ':proj-shared-resources:jar'`, since processResources consumes the output of that task.
Please let me know, if it solves the problem for you.

**Comment by johnjaylward** [comment]
Yes, the error I was seeing made it look gradle 3 related since it wasn't an issue with gradle 2. Those changes do seem to have fixed it. I had no idea that using {} instead of () changed when the call would be made.

Thanks for the help!
