### ISSUE TITLE
Gradle 3.3 compatibility work breaks earlier versions of Gradle

### ISSUE THREAD

**Issue by DanielThomas** [akhikhl/gretty#326]
`DummyTask` imports an internal class that's Gradle 3.x specific:

    Caused by: java.lang.NoClassDefFoundError: org/gradle/api/internal/TaskInputsInternal
        at org.akhikhl.gretty.StartBaseTask.getJacoco(StartBaseTask.groovy:132)
        at org.akhikhl.gretty.TomcatStartTask_Decorated.getJacoco(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.doPrepareServerConfig(StartBaseTask.groovy:96)
        at org.akhikhl.gretty.AppStartTask.getStartConfig(AppStartTask.groovy:53)
        at org.akhikhl.gretty.TomcatStartTask_Decorated.getStartConfig(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.getLauncherConfig(StartBaseTask.groovy:141)
        at org.akhikhl.gretty.StartBaseTask.action(StartBaseTask.groovy:39)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
    Caused by: java.lang.ClassNotFoundException: org.gradle.api.internal.TaskInputsInternal
        ... 75 more

**Comment by akhikhl** [comment]
Resolved with pull request #340 . Solution will be delivered with the release 1.4.2.
