### ISSUE TITLE
gretty 1.4.1 and gradle 3.3 issue

### ISSUE THREAD

**Issue by anishaNair** [akhikhl/gretty#329]
when i run my gradle jettyStart i'm getting an illegalStateException error like below.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jettyStart'.
> Cannot call TaskInputs.property(String, Object) on task ':jettyStart' after task has started execution.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

this is my build.gradle entry for gretty

apply plugin: 'org.akhikhl.gretty'
gretty {
    servletContainer = 'jetty9'
    contextPath = '/notifications'
    jvmArgs = ["-DdeviceLinkConfigFile=file:./Configs/jetty.properties"]
    serverConfigFile = "./jetty/jetty-DL.xml"
    httpPort = 8085
}

Let me know if this info is not sufficient

**Comment by kevto** [comment]
I'm experiencing the very same issue.

This is my setup.
![image](https://cloud.githubusercontent.com/assets/10073027/22782546/d90e4a8e-eec7-11e6-8a1a-da2bc785af16.png)

**Comment by zhaitao** [comment]
Same issue here, see stacktrace below:

Caused by: java.lang.IllegalStateException: Cannot call TaskInputs.property(String, Object) on task
        at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:38)
        at org.gradle.api.internal.tasks.DefaultTaskInputs.property(DefaultTaskInputs.java:201)
        at org.gradle.testing.jacoco.plugins.JacocoPluginExtension.applyTo(JacocoPluginExtension.java:104)
        at org.gradle.testing.jacoco.plugins.JacocoPluginExtension$applyTo.call(Unknown Source)
        at org.akhikhl.gretty.JacocoHelper.<init>(JacocoHelper.groovy:32)
        at org.akhikhl.gretty.StartBaseTask.getJacoco(StartBaseTask.groovy:132)

I'm on gradle 3.3, gretty 1.4.1, jacoco { toolVersion = '0.7.7.201606060606' }

**Comment by vkdot** [comment]
I experienced the same issue, but found a workaround:
- remove following from your build.gradle
`apply plugin: "jacoco"`
`build.dependsOn jacocoTestReport`

**Comment by kurra** [comment]
I am experiencing the same issue. I have tried with both Gradle 3.3 and Gradle 3.4 with latest gretty plugin 1.4.1

**Comment by gunalmel** [comment]
I am getting the same issue with gradle 3.4.1. StackTrace:

```
Caused by: java.lang.IllegalStateException: Cannot call TaskInputs.property(String, Object) on task ':jettyStart' after task has started execution.
        at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:38)
        at org.gradle.api.internal.tasks.DefaultTaskInputs.property(DefaultTaskInputs.java:202)
        at org.gradle.testing.jacoco.plugins.JacocoPluginExtension.applyTo(JacocoPluginExtension.java:102)
        at org.gradle.testing.jacoco.plugins.JacocoPluginExtension$applyTo.call(Unknown Source)
        at org.akhikhl.gretty.JacocoHelper.<init>(JacocoHelper.groovy:32)
        at org.akhikhl.gretty.StartBaseTask.getJacoco(StartBaseTask.groovy:132)
        at org.akhikhl.gretty.JettyStartTask_Decorated.getJacoco(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.doPrepareServerConfig(StartBaseTask.groovy:96)
        at org.akhikhl.gretty.AppStartTask.getStartConfig(AppStartTask.groovy:53)
        at org.akhikhl.gretty.JettyStartTask_Decorated.getStartConfig(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.getLauncherConfig(StartBaseTask.groovy:141)
        at org.akhikhl.gretty.StartBaseTask.action(StartBaseTask.groovy:39)

```

**Comment by akhikhl** [comment]
Resolved in #339 . Solution will be delivered with Gretty 1.4.2.

**Comment by chenrui333** [comment]
Gretty 1.4.2 works for me with Gradle 3.4.1

**Comment by zhaitao** [comment]
1.4.2 works for me too. Thanks for the fix!

**Comment by gunalmel** [comment]
1.4.2 with Gradle 3.4.1 worked for me as well even after enabling jacoco in gretty plugin configuration. Thank you!
