### ISSUE TITLE
gretty 1.4.1 breaks buildProduct

### ISSUE THREAD

**Issue by h3adache** [akhikhl/gretty#331]
When using Gradle 3.3
```
* What went wrong:
Could not determine the dependencies of task ':view:buildProduct'.
> Cannot set readonly property: webAppRefs_ for class: org.akhikhl.gretty.FarmExtension
```

**Comment by h3adache** [comment]
https://github.com/akhikhl/gretty/commit/cb2564737b323c8717aba17a35e2453ee086a9dd
This is the commit that broke it. Turning webAppRefs_ to final

**Comment by akosyakov** [comment]
@akhikhl when the fix could be expected? it makes the new version unusable. Is there a workaround?

**Comment by sluggard6** [comment]
the same problem
`
Caused by: groovy.lang.ReadOnlyPropertyException: Cannot set readonly property: webAppRefs_ for class: org.akhikhl.gretty.FarmExtension
        at org.akhikhl.gretty.FarmConfig.setProperty(FarmConfig.groovy)
        at org.akhikhl.gretty.FarmConfigurer.configureFarm(FarmConfigurer.groovy:42)
        at org.akhikhl.gretty.ProductConfigurer.resolveConfig(ProductConfigurer.groovy:367)
        at org.akhikhl.gretty.ProductConfigurer$_configureProduct_closure1$_closure13.doCall(ProductConfigurer.groovy:56)
        at org.gradle.api.internal.tasks.DefaultTaskDependency.visitDependencies(DefaultTaskDependency.java:69)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveCo
        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmpyEdges.getNodeValues(CachingDirectedGraphWalker.java:202)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:112)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:64)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.doResolve(CachingTaskDependencyResolveContext.java:76)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:65)
        ... 89 more
`

**Comment by Gillingham** [comment]
This is happening in gradle 3.4.1 as well, and also in gretty 1.4.2. The fix for now is to downgrade to gretty 1.4.0

**Comment by ItachiSan** [comment]
Similar error here with [this code](https://github.com/ItachiSan/programming_class/tree/master/distributed_systems):
```
> gradle server:buildAllProducts

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':server:buildProduct'.
> Cannot set readonly property: webAppRefs_ for class: org.akhikhl.gretty.FarmExtension

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.521 secs
```
Downgrading to *1.4.0* did the trick for me.

**Comment by h3adache** [comment]
2.0.0 fixes this
