### ISSUE TITLE
Object of class 'org.eclipse.jetty.server.Server' is not of type 'org.eclipse.jetty.server.handler.ContextHandler'

### ISSUE THREAD

**Issue by typekpb** [akhikhl/gretty#347]
Serving static contents with jetty 9.3 fails with gretty, but works OK with plain jetty (9.3.8.v20160314).

Official jetty docs [recommends](http://www.eclipse.org/jetty/documentation/current/static-content-deployment.html) using following config file:

	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
	<Configure class="org.eclipse.jetty.server.handler.ContextHandler">
	  <Set name="contextPath">/<Set>
	  <Set name="handler">
	    <New class="org.eclipse.jetty.server.handler.ResourceHandler">
	      <Set name="resourceBase">./</Set>
	      <Set name="directoriesListed">true</Set>
	    </New>
	  </Set>
	</Configure>

However once using following `build.gradle`:

	buildscript {
	  repositories {
	      jcenter()
	  }
	  dependencies {
	      classpath 'org.akhikhl.gretty:gretty:1.4.2'
	  }
	}

	repositories {
	  jcenter()
	}

	apply plugin: 'java'
	apply plugin: 'war'
	apply plugin: 'org.akhikhl.gretty'

	gretty {
	  httpPort = 8082
	  serverConfigFile = 'jetty-static-content.xml'
	  contextPath = '/'
	  servletContainer='jetty9.3'
	}

I get error on command:

	Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
	:clean
	:prepareInplaceWebAppFolder NO-SOURCE
	:createInplaceWebAppFolder
	:compileJava NO-SOURCE
	:processResources NO-SOURCE
	:classes UP-TO-DATE
	:prepareInplaceWebAppClasses UP-TO-DATE
	:prepareInplaceWebApp
	:appBeforeIntegrationTest
	11:15:31 INFO  Configuring server with /home/pb/foo/jetty-static-content.xml
	Exception in thread "main" java.lang.IllegalArgumentException: Object of class 'org.eclipse.jetty.server.Server' is not of type 'org.eclipse.jetty.server.handler.ContextHandler'.  in file:/home/pb/foo/jetty-static-content.xml
		at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:295)
		at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:245)
		at org.eclipse.jetty.xml.XmlConfiguration$configure.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
		at org.akhikhl.gretty.JettyConfigurerImpl.applyJettyXml(JettyConfigurerImpl.groovy:64)
		at org.akhikhl.gretty.JettyConfigurer$applyJettyXml$0.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
		at org.akhikhl.gretty.JettyServerConfigurer.createAndConfigureServer(JettyServerConfigurer.groovy:61)
		at org.akhikhl.gretty.JettyServerConfigurer.createAndConfigureServer(JettyServerConfigurer.groovy)
		at org.akhikhl.gretty.JettyServerConfigurer$createAndConfigureServer.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
		at org.akhikhl.gretty.JettyServerManager.startServer(JettyServerManager.groovy:41)
		at org.akhikhl.gretty.ServerManager$startServer$0.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
		at org.akhikhl.gretty.Runner.run(Runner.groovy:117)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
		at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
		at org.akhikhl.gretty.Runner.main(Runner.groovy:44)
	Exception in thread "Thread-14" org.gradle.process.internal.ExecException: Process 'command '/home/pb/jdk1.8.0_112/bin/java'' finished with non-zero exit value 1
		at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:369)
		at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
		at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:170)
		at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:914)
		at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:910)
		at org.gradle.api.Project$javaexec$6.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
		at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:89)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
		at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
		at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy:256)
		at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
		at groovy.lang.Closure.call(Closure.java:414)
		at groovy.lang.Closure.call(Closure.java:408)
		at groovy.lang.Closure.run(Closure.java:495)
		at java.lang.Thread.run(Thread.java:745)

**Comment by hongminzhu** [comment]
Yea I  have the same issue trying to setup a JNDI entry.. any updates on this?
