### ISSUE TITLE
gretty fails to load context for javax.json-api (module-info.class) - any suggestions ?

### ISSUE THREAD

**Issue by sivaswami** [akhikhl/gretty#360]
00:19:51 WARN  Failed startup of context o.a.g.JettyWebAppContext@47a5b70d{/mycode,file:/D:/workspace/mycode/build/inplaceWebapp/,STARTING}
java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/C:/.gradle/caches/modules-2/files-2.1/javax.json/javax.json-api/1.1.0-M2/3aca4577ff2a4fc06eb447e6f6d1e075f5a1f1bf/javax.json-api-1.1.0-M2.jar
        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913) ~[jetty-annotations-9.2.15.v20160210.jar:9.2.15.v20160210]
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:831) ~[jetty-annotations-9.2.15.v20160210.jar:9.2.15.v20160210]
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:164) ~[jetty-annotations-9.2.15.v20160210.jar:9.2.15.v20160210]
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:549) ~[jetty-annotations-9.2.15.v20160210.jar:9.2.15.v20160210]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) ~[jetty-util-9.2.15.v20160210.jar:9.2.15.v20160210]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) ~[jetty-util-9.2.15.v20160210.jar:9.2.15.v20160210]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: null
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:973) ~[jetty-annotations-9.2.15.v20160210.jar:9.2.15.v20160210]
        at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956) ~[jetty-annotations-9.2.15.v20160210.jar:9.2.15.v20160210]
        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909) ~[jetty-annotations-9.2.15.v20160210.jar:9.2.15.v20160210]
        ... 6 common frames omitted
00:19:51 INFO  Jetty 9.2.15.v20160210 started and listening on port 8080
00:19:51 INFO  oscs runs at:
00:19:51 INFO    http://localhost:8080/oscs
> Building 94% > :appRun

**Comment by dylanbehetre** [comment]
Same problem with this gradle.build : 

plugins {
    id 'java'
    id 'war'
    id "org.akhikhl.gretty" version "2.0.0"
}

repositories {
    jcenter()
    mavenCentral()
}

ext {
    jerseyVersion = '2.26-b09'
    log4jVersion = '2.8.2'
}

dependencies {
    /* All .JAR in the "libs" directory :
    - vim25.jar : API VSphere web service to request VSphere Server
     */
    compile fileTree(dir: 'libs', include: '*.jar')

    // Framework Jersey to create a web service :
    // https://mvnrepository.com/artifact/org.glassfish.jersey.core/jersey-server
    compile "org.glassfish.jersey.core:jersey-server:${jerseyVersion}"
    compile "org.glassfish.jersey.containers:jersey-container-servlet:${jerseyVersion}"
    compile "org.glassfish.jersey.inject:jersey-hk2:${jerseyVersion}"

    // API to manipulate JSON :
    // https://mvnrepository.com/artifact/org.glassfish/javax.json
    compile 'javax.json:javax.json-api:1.1'
    compile 'org.glassfish:javax.json:1.1'

    // API LOG4J through the abstract API SLF4J to manage logs
    compile "org.apache.logging.log4j:log4j-slf4j-impl:${log4jVersion}"
    compile "org.apache.logging.log4j:log4j-core:${log4jVersion}"

    // API JUnit to create unit test :
    testCompile 'junit:junit:4.12'
}

gretty { // http://akhikhl.github.io/gretty-doc/Gretty-configuration.html
    servletContainer = 'jetty9'
    host = "localhost"
    httpPort = 8080
    contextPath = "/middleTier"
    jvmArgs = ["-DconfigPath=config/config.json", "-Dlog4j.configurationFile=src/main/ressources/log4j2.xml"]
    integrationTestTask = 'test'
}

**Comment by motleycodes** [comment]
I had some problems with module-info.class in Wildfly, here is how I resolved them: https://stackoverflow.com/questions/44804417/update-javax-json-from-1-0-2-to-1-1/46935693#46935693 maybe it'll work for gretty?

**Comment by msangel** [comment]
Still actual. 

env
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
Gradle 4.10
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Linux 4.8.17-hidden amd64

```

traces: 
```
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:1.8.0_181]
	at org.eclipse.jetty.annotations.ClassInheritanceHandler.addToInheritanceMap(ClassInheritanceHandler.java:72) ~[jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.ClassInheritanceHandler.handle(ClassInheritanceHandler.java:58) ~[jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.visit(AnnotationParser.java:480) [jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:492) [asm-6.1.1.jar:na]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:355) [asm-6.1.1.jar:na]
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974) [jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956) [jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909) [jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:831) [jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:164) [jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:549) [jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.24.v20180105.jar:9.2.24.v20180105]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
00:49:39 WARN  Failed startup of context o.a.g.JettyWebAppContext@4b14918a{/,file:/home/user/project/build/inplaceWebapp/,STARTING}
java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/home/user/.gradle/caches/modules-2/files-2.1/javax.json/javax.json-api/1.1.2/b38c52a6e180359108bd5e35dbeec7d1be45c535/javax.json-api-1.1.2.jar
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913) ~[jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:831) ~[jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:164) ~[jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:549) ~[jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) ~[jetty-util-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) ~[jetty-util-9.2.24.v20180105.jar:9.2.24.v20180105]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.UnsupportedOperationException: null
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:129) ~[asm-6.1.1.jar:na]
	at org.objectweb.asm.ClassReader.readModule(ClassReader.java:667) ~[asm-6.1.1.jar:na]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:503) ~[asm-6.1.1.jar:na]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:355) ~[asm-6.1.1.jar:na]
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:974) ~[jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:956) ~[jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:909) ~[jetty-annotations-9.2.24.v20180105.jar:9.2.24.v20180105]
	... 6 common frames omitted
```

**Comment by javabrett** [comment]
@msangel Do you need to run Jetty 9.2, could you move up to say 9.4.x?

This sort of issue is becoming more-frequently reported as certain public jars include JDK9 `module-info.class` and some annotation scanners can't handle them.  Jetty 9.2.x has no support for this, and can find issue with such JDK9-ready jars.  This has been fixed I believe in Jetty 9.4.x, and IIRC may have been backported to 9.3.x but not 9.2.x.

**Comment by msangel** [comment]
Simply change the jetty version to latest `jetty9Version = 9.4.12.v20180830` (as documentation says to do it) cause this: 
```
Exception in thread "Thread-45" org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':grettyRunnerJetty9'.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1054)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1700(DefaultConfiguration.java:123)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1028)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:444)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:299)
	at org.akhikhl.gretty.DefaultLauncher.getRunnerClassPath(DefaultLauncher.groovy:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:78)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
	at org.akhikhl.gretty.DefaultLauncher$_javaExec_closure7.doCall(DefaultLauncher.groovy:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
	at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:224)
	at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1102)
	at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1097)
	at org.gradle.api.Project$javaexec$6.call(Unknown Source)
	at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy:256)
	at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.run(Closure.java:499)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.eclipse.jetty:jetty-jsp:9.4.12.v20180830.
Searched in the following locations:
  - https://jcenter.bintray.com/org/eclipse/jetty/jetty-jsp/9.4.12.v20180830/jetty-jsp-9.4.12.v20180830.pom
  - https://jcenter.bintray.com/org/eclipse/jetty/jetty-jsp/9.4.12.v20180830/jetty-jsp-9.4.12.v20180830.jar
Required by:
    project : > org.gretty:gretty-runner-jetty9:2.2.0
	at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:49)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:108)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:63)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:94)
	at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:62)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.resolve(ComponentState.java:208)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.resolve(ComponentState.java:196)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.getMetadata(ComponentState.java:152)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DownloadMetadataOperation.run(DownloadMetadataOperation.java:31)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.access$900(DefaultBuildOperationExecutor.java:48)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$ParentPreservingQueueWorker.execute(DefaultBuildOperationExecutor.java:342)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:230)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.access$600(DefaultBuildOperationQueue.java:172)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.call(DefaultBuildOperationQueue.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.call(DefaultBuildOperationQueue.java:203)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:203)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:177)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	... 1 more
> Task :appRun
```

The only latest available is:
`compile group: 'org.eclipse.jetty', name: 'jetty-jsp', version: '9.2.26.v20180806'`

So this also should be fixed separately. And how do I override the jetty-jsp version?

**Comment by msangel** [comment]
The same result

libs

```
java version "1.8.0_181"
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
Gradle 4.10
id 'org.gretty' version '2.2.0'
servletContainer = 'jetty9.4'
jetty94Version = 9.4.6.v20170531
```


the traces: 

```
13:48:24 WARN  
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:1.8.0_181]
	at org.eclipse.jetty.annotations.ClassInheritanceHandler.addToInheritanceMap(ClassInheritanceHandler.java:73) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.ClassInheritanceHandler.handle(ClassInheritanceHandler.java:59) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.visit(AnnotationParser.java:476) [jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:492) [asm-6.1.1.jar:na]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:355) [asm-6.1.1.jar:na]
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:960) [jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:940) [jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:887) [jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:837) [jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159) [jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:462) [jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
13:48:25 WARN  Failed startup of context o.a.g.JettyWebAppContext@2c1156a7{/,file:///home/user/project/build/inplaceWebapp/,UNAVAILABLE}
java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///home/user/.gradle/caches/modules-2/files-2.1/javax.json/javax.json-api/1.1.2/b38c52a6e180359108bd5e35dbeec7d1be45c535/javax.json-api-1.1.2.jar
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:891) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:837) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:462) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673) ~[jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591) ~[jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.UnsupportedOperationException: null
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:129) ~[asm-6.1.1.jar:na]
	at org.objectweb.asm.ClassReader.readModule(ClassReader.java:667) ~[asm-6.1.1.jar:na]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:503) ~[asm-6.1.1.jar:na]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:355) ~[asm-6.1.1.jar:na]
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:960) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:940) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:887) ~[jetty-annotations-9.4.6.v20170531.jar:9.4.6.v20170531]
	... 6 common frames omitted
13:48:25 INFO  Jetty 9.4.6.v20170531 started and listening on port 8080
13:48:26 INFO   runs at:
13:48:26 INFO    http://localhost:8080/
```

**Comment by msangel** [comment]
Ok, the bug seems to be fixed in snapshots, only in 9.4.12 and 9.4.7 (9.4.6 yet dont have it)

https://github.com/eclipse/jetty.project/commit/187f37dc5f8f14f83ab2e263283ab48848d6d9a9

Have no time now to check, but in the evening will do that (if someone will not do it earlier)

**Comment by msangel** [comment]
Ok, I tested it now.
jetty94Version = 9.4.7.v20170914
Works without the issue. 
So for fixing this the gretty configuration must have minimum 9.4 `servletContainer = 'jetty9.4'` property and the minimal jetty version in `gradle.properties` must be minimum 9.4.7 
`jetty94Version = 9.4.7.v20170914`

The issue can be closed now, thanks.

**Comment by johndevs** [comment]
I can confirm it working between jetty versions `9.4.7.v20170914` to `9.4.12.v20180830`. 

With `9.4.13.v20181111` and forward it is broken again.

**Comment by javabrett** [comment]
Jetty 9.4.13 switched to ASM 7.0 and Gretty needed to upgrade. This is done on 2.x branch (of the fork) pending release. Snapshots are available for testing. 

What's this simplest test for this issue?

**Comment by ksrb** [comment]
For those who stumble upon this from google  the project has set [jetty94_version = 9.4.14.v20181114 ](https://github.com/gretty-gradle-plugin/gretty/blob/73ce69e6cf9b497d74c2b35260646e144c0cef6d/gradle.properties#L16) at some point so you just need to do:

**build.gradle**
```gradle
gretty {
    servletContainer = 'jetty9.4'
}
```
