### ISSUE TITLE
Cannot find resources in inplace mode

### ISSUE THREAD

**Issue by Gontran08** [akhikhl/gretty#382]
I can't find my resources if I try to execute my app using appRun/appRunDebug. If I use ResourceBundle.getBundle, I get a MissingResourceException. I used appRunWar/appRunWarDebug to fix the problem, but I need to execute tests and the task appBeforeIntegrationTest has the same behavior. To be precise, I can get test resources, but not those coming from the main app. I tried adding them to the tests using the sourceSets property, but even if they are in build/resources/test, my app can't see them.

> javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
>     	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:662)
>     	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
>     	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:350)
>     	at javax.naming.InitialContext.lookup(InitialContext.java:417)

> java.util.MissingResourceException: Can't find bundle for base name conf.config, locale fr_CA
>     	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
>     	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
>     	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)

**Comment by Gontran08** [comment]
It was related with our code.
