### ISSUE TITLE
Cannot be used with SpringBoot due to lower logback

### ISSUE THREAD

**Issue by xtuer** [akhikhl/gretty#387]
Latest Gretty cannot be used with SpringBoot due to Gretty use logback 1.1.3 that overrides the SpringBoot's logback, the exceptions is:

java.lang.AbstractMethodError: ch.qos.logback.classic.pattern.EnsureExceptionHandling.process(Lch/qos/logback/core/Context;Lch/qos/logback/core/pattern/Converter;)V
        at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:86)
        at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
        at ch.qos.logback.classic.BasicConfigurator.configure(BasicConfigurator.java:50)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:164)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.apache.commons.logging.LogFactory$Slf4jDelegate.createLocationAwareLog(LogFactory.java:174)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:111)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:99)
        at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:198)
        at com.example.demo.DemoApplication.main(DemoApplication.java:10)

**Comment by wendlm** [comment]
I encounter exactly the same problem

**Comment by tveimo** [comment]
I think this happens if you include the spring boot gradle plugin:

classpath("org.springframework.boot:spring-boot-gradle-plugin:1.5.10.RELEASE")

Try removing it.
