### ISSUE TITLE
gretty doesn't work with spring boot 1.5.2.RELEASE

### ISSUE THREAD

**Issue by tkgospodinov** [akhikhl/gretty#392]
Our application does not start when applying gretty:2.0.0 in conjunction with spring-boot:1.5.2.RELEASE, throwing the exception below. The root cause seems to be a conflict between the version of logback-core that spring-boot is using and the version of logback-classic version gretty is injecting:
```
...
|    |    +--- org.springframework.boot:spring-boot-starter-logging:1.5.2.RELEASE
|    |    |    +--- ch.qos.logback:logback-classic:1.1.11 -> 1.1.3
|    |    |    |    +--- ch.qos.logback:logback-core:1.1.3 -> 1.1.11
...
+--- ch.qos.logback:logback-classic:1.1.3 (*)
...
```
Exception when running with `gradle jettyRun`:
```
16:12:53 ERROR Error starting server
java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer not found
        at java.util.ServiceLoader.fail(ServiceLoader.java:239)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.eclipse.jetty.annotations.AnnotationConfiguration.getNonExcludedInitializers(AnnotationConfiguration.java:786)
        at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:362)
        at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:512)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1437)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:799)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:540)
        at org.akhikhl.gretty.JettyWebAppContext.super$10$doStart(JettyWebAppContext.groovy)
...
```
Relevant configuration from the build file:
```
buildscript {
    repositories {
        ...
    }
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.5.2.RELEASE'
        classpath 'org.akhikhl.gretty:gretty:2.0.0'
    }
}
```
Proposed fix: Make the logback version configurable through the gretty extension, similar to the spring boot version.

`GrettyPlugin.groovy`:
```
  private void addDependencies(Project project) {
    ...
    String logbackVersion = project.gretty.logbackVersion ?: (project.hasProperty('logbackVersion') ? project.logbackVersion :Externalized.getString('logbackVersion'))
    ...
  }
```

**Comment by bmuschko** [comment]
Can you explain why you even need the Gretty plugin for a Spring Boot project? Spring Boot provides dependencies for starting the application with either Tomcat or Jetty.
