### ISSUE TITLE
NoClassDefFoundError: HashSessionManager (was fixed?)

### ISSUE THREAD

**Issue by bvn13** [akhikhl/gretty#404]
I'm newbie in gradle. Trying to run https://github.com/mintster/nixmash-blog

Added gretty like described into http://akhikhl.github.io/gretty-doc/Getting-started.html

```
apply plugin: 'war'
apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'
```

And when I ran it, the following error occured:

```
:appRunException in thread "main" java.lang.NoClassDefFoundError: Lorg/eclipse/jetty/server/session/HashSessionManager;
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.getDeclaredFields(Class.java:1916)
        at org.codehaus.groovy.reflection.CachedClass$1$1.run(CachedClass.java:54)
        at org.codehaus.groovy.reflection.CachedClass$1$1.run(CachedClass.java:52)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.codehaus.groovy.reflection.CachedClass$1.initValue(CachedClass.java:52)
        at org.codehaus.groovy.reflection.CachedClass$1.initValue(CachedClass.java:49)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:49)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:36)
        at org.codehaus.groovy.reflection.CachedClass.getFields(CachedClass.java:278)
        at groovy.lang.MetaClassImpl.addFields(MetaClassImpl.java:2385)
        at groovy.lang.MetaClassImpl.inheritFields(MetaClassImpl.java:2380)
        at groovy.lang.MetaClassImpl.setupProperties(MetaClassImpl.java:2267)
        at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3328)
        at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3293)
        at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:260)
        at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:302)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:261)
        at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:883)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:75)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:162)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.akhikhl.gretty.ServerManagerFactory.createServerManager(ServerManagerFactory.groovy:19)
        at org.akhikhl.gretty.ServerManagerFactory$createServerManager.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.akhikhl.gretty.Runner.run(Runner.groovy:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.akhikhl.gretty.Runner.main(Runner.groovy:44)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.session.HashSessionManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 41 more
```

**Comment by ghost** [comment]
I have same problem when i use gretty 2.0 with spring boot 1.5.8 Release

**Comment by Oceanedge** [comment]
Same issue for me.

**Comment by javabrett** [comment]
You'll need to force Gretty to use Jetty 9.4 e.g.:

```
gretty {
       servletContainer = 'jetty9.4'
       jetty94Version = '9.4.9.v20180320'
}
```
I also tested with the gretty.org fork, so `apply from: 'https://raw.github.com/gretty-gradle-plugin/gretty/master/pluginScripts/gretty-SNAPSHOT.plugin'` and used `springBootVersion = '1.5.9.RELEASE'`.
