### ISSUE TITLE
java.lang.NullPointerException   in relation to springboot, gretty gradel plugin , weblogic  /wls-12.2.1.x

### ISSUE THREAD

**Issue by alan-techdev** [akhikhl/gretty#411]
springBootVersion = '1.5.9.RELEASE'

stack below:

Caused By: java.lang.NullPointerException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.akhikhl.gretty.AppServletInitializer.configure(AppServletInitializer.java:17)
        at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:121)
        at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:87)

we suspect:
AppServletInitializer.setSpringBootMainClass  is not being invoked  and the static  attribute is null
  public static String springBootMainClass;  // this is null

question:
Where is the configuration  to set the main class for AppServletInitializer

**Comment by tveimo** [comment]
Am having the same issue, did you find a workaround? The app works when deploying with appRun, but fails when packaging to a war file.

**Comment by alan-techdev** [comment]
Tveimo,
Not sure. I did a lot of changed.  One of them is I removed the jetty plugin and I fixed the weblogic issue. 
Now I can run the application from weblogic 12.** and ecliplse directly as well as deploy it into tomcat. 
I recommend to use tomcat plugin directly  instead of getty. 
In summary, I am not using gretty plugin anymore from gradle.
