### ISSUE TITLE
ClassNotFoundException even though the dependency is included

### ISSUE THREAD

**Issue by ahoxha** [akhikhl/gretty#412]
I am trying to change the logging manager by setting the system property as below:

    gretty {
	    servletContainer = 'tomcat8'
 	    httpPort = 8081
 	    jvmArg '-Dlog4j.configurationFile=lib/log4j2.xml'
 	    systemProperty 'java.util.logging.manager', 'org.apache.logging.log4j.jul.LogManager'
    }

But I'm getting this error:

    Could not load Logmanager "org.apache.logging.log4j.jul.LogManager"
    java.lang.ClassNotFoundException: org.apache.logging.log4j.jul.LogManager
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at java.util.logging.LogManager$1.run(LogManager.java:195)
		at java.util.logging.LogManager$1.run(LogManager.java:181)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.util.logging.LogManager.(LogManager.java:181)
		at java.util.logging.Logger.demandLogger(Logger.java:448)
		at java.util.logging.Logger.getLogger(Logger.java:502)
		at org.codehaus.groovy.runtime.DefaultGroovyMethodsSupport.(DefaultGroovyMethodsSupport.java:37)
		at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.(MetaClassRegistryImpl.java:97)
		at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.(MetaClassRegistryImpl.java:74)
		at groovy.lang.GroovySystem.(GroovySystem.java:36)
		at org.codehaus.groovy.runtime.InvokerHelper.(InvokerHelper.java:66)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:87)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:239)
		at org.akhikhl.gretty.Runner.main(Runner.groovy:36)

Here's the dependencies section: 

    dependencies {
        compile "javax.ws.rs:javax.ws.rs-api:2.1"
        compile "org.glassfish.jersey.core:jersey-server:2.22.1"
        compile "org.glassfish.jersey.containers:jersey-container-servlet:2.22.1"
        compile "org.glassfish.jersey.media:jersey-media-json-jackson:2.22.1" 
        providedCompile "javax.servlet:javax.servlet-api:3.1.0" 
	
        compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.8'
        compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.8'
        compile group: 'org.apache.logging.log4j', name: 'log4j-web', version: '2.8'
        compile group: 'org.apache.logging.log4j', name: 'log4j-jul', version: '2.8'
 	
        compile files('lib/loggen.jar') // this lib generates logs using JUL, for testing purposes only
    }

**Comment by javabrett** [comment]
@ahoxha are you able to share a redacted but full project which demonstrates this error?

**Comment by javabrett** [comment]
@ahoxha never mind I can reproduce this and think I understand the cause.  I will write it up as a bug in gretty-gradle-plugin/gretty .

**Comment by ahoxha** [comment]
@javabrett  Sorry for the late response! I was planning on creating a minimal project tonight. But since you got it, then I won't. Thanks for your help!
