### ISSUE TITLE
Gretty with Gradle 4.6 results in Could not create task of type 'AppStartTask' when running any gradle task.  NPE in JacocoPluginExtension.applyTo(JacocoPluginExtension.java:117)

### ISSUE THREAD

**Issue by gunalmel** [akhikhl/gretty#425]
**Workaround:** Using the workaround reported in http://akhikhl.github.io/gretty-doc/Code-coverage-support.html 

```
gretty {
	jacocoEnabled false
}
```

which was previously fixed in https://github.com/akhikhl/gretty/pull/339 for an earlier version.

When gradle build task is called with -- stacktrace:

```
> Could not create task of type 'AppStartTask'.
Caused by: java.lang.NullPointerException
        at org.gradle.testing.jacoco.plugins.JacocoPluginExtension.applyTo(JacocoPluginExtension.java:117)
        at org.gradle.testing.jacoco.plugins.JacocoPluginExtension$applyTo.call(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.initJacoco(StartBaseTask.groovy:156)
        at org.akhikhl.gretty.StartBaseTask.<init>(StartBaseTask.groovy:41)
        at org.akhikhl.gretty.AppStartTask.<init>(AppStartTask.groovy)
        at org.akhikhl.gretty.AppStartTask_Decorated.<init>(Unknown Source)
        at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:81)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:119)
```

**Comment by javabrett** [comment]
Duplicates #420.  Fixed in https://github.com/gretty-gradle-plugin/gretty/pull/3 .
