### ISSUE TITLE
For a non spring boot application, gretty is complaining for spring boot dependency

### ISSUE THREAD

**Issue by dhamep** [akhikhl/gretty#456]
I have upgraded the gretty version 1.1.2 to 3.0.6. since then its failing at 
Caused by: org.gradle.api.GradleException: Could not generate a proxy class for class org.akhikhl.gretty.AppBeforeIntegrationTestTask.
at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:220)
at org.gradle.api.internal.AbstractClassGenerator.generate(AbstractClassGenerator.java:49)
at org.gradle.api.internal.project.taskfactory.TaskFactory.createTaskObject(TaskFactory.java:116)
at org.gradle.api.internal.project.taskfactory.TaskFactory.createTask(TaskFactory.java:81)
at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.createTask(AnnotationProcessingTaskFactory.j
......
at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
... 104 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/devtools/autoconfigure/OptionalLiveReloadServer
at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:112)
... 120 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.devtools.autoconfigure.OptionalLiveReloadServer

Indeed we do have this following setting
void excludeUnneededGrettyDependencies() {
// we do not need hot appl redeploy and this allows us to 
// get rid of unwanted spring boot  3rd party dependencies  
project.gretty {
 springBoot = false    
}

Because of which earlier version 1.1.2 version didn't complains for spring boot dependency.
Can you please confirm why this is complaining now? Or any specific version i can use to get rid of this error?

**Comment by boris-petrov** [comment]
@dhamep - if you still get that issue, please open an issue in the [new repo](https://github.com/gretty-gradle-plugin/gretty).
