### ISSUE TITLE
Custom builds of Gradle cause NumberFormatException

### ISSUE THREAD

**Issue by quidryan** [akhikhl/gretty#96]
On https://github.com/akhikhl/gretty/blob/master/libs/gretty/src/main/groovy/org/akhikhl/gretty/GrettyPlugin.groovy#L583:

```
int releaseNumber = project.gradle.gradleVersion.split('\\.')[1] as int
```

This assumes that the second part of the split is a simple number. In my case, I have a custom build (or a snapshot build of Gradle) which looks like this: 1.12-20140612154955+0000. That causes this exception:

```
Caused by: java.lang.NumberFormatException: For input string: "12-20140612154955+0000"
  at org.akhikhl.gretty.GrettyPlugin.apply(GrettyPlugin.groovy:580)
  at org.akhikhl.gretty.GrettyPlugin.apply(GrettyPlugin.groovy)
  at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:104)
  at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:68)
  at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:34)
```

**Comment by akhikhl** [comment]
Hi Justin,
Does Gretty 1.1.8 fix this bug for you?
